# Generated by Django 4.2.1 on 2023-05-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_vendor_active_vendor_vocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='is_scheduled',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='conversation',
            new_name='most_recent_conversation',
        ),
    ]
