# Generated by Django 4.2.1 on 2023-05-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_rename_is_scheduled_conversation_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
