# Generated by Django 4.2.1 on 2023-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_alter_conversation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='is_base_number',
            field=models.BooleanField(default=False),
        ),
    ]
