# Generated by Django 4.2.1 on 2023-05-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_phonenumber_is_base_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
