# Generated by Django 4.2.1 on 2023-06-09 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_message_receiver_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='most_recent_conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twilio_number', to='conversations.conversation'),
        ),
        migrations.CreateModel(
            name='MediaMessageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.URLField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, choices=[('image', 'image'), ('video', 'video'), ('unknown', 'unknown')], max_length=200, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_message_contents', to='conversations.message')),
            ],
        ),
    ]
