# Generated by Django 4.2.1 on 2023-06-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0008_alter_phonenumber_most_recent_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mediamessagecontent',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'image'), ('video', 'video'), ('other', 'other')], max_length=200, null=True),
        ),
    ]
