# Generated by Django 4.2.1 on 2023-07-02 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_assistant_phone_number'),
        ('conversations', '0011_conversation_proposed_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
    ]
