# Generated by Django 4.2.1 on 2023-07-14 03:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_street_company_street_1_and_more'),
        ('conversations', '0011_conversation_proposed_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='vendor_detection_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
