# Generated by Django 4.2.1 on 2023-07-02 22:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0012_vendor_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
