# Generated by Django 4.2.1 on 2023-07-25 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_transaction'),
        ('conversations', '0012_conversation_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='companies.company'),
        ),
    ]
