# Generated by Django 4.2.1 on 2023-07-08 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_assistant_phone_number'),
        ('conversations', '0013_alter_vendor_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
    ]
