# Generated by Django 4.2.1 on 2023-07-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0013_alter_conversation_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='has_opted_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
