# Generated by Django 4.2.1 on 2023-08-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0015_conversation_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='point_of_contact_has_interjected',
            field=models.BooleanField(default=False),
        ),
    ]
