# Generated by Django 4.2.1 on 2023-08-22 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_point_of_contact'),
        ('conversations', '0015_conversation_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_phone_number_object', to='companies.company'),
        ),
    ]
