# Generated by Django 4.2.1 on 2023-07-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0015_message_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='vendor_detection_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
