# Generated by Django 4.2.1 on 2023-08-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0016_conversation_point_of_contact_has_interjected'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='tenant_intro_message',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='vendor_intro_message',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
