# Generated by Django 4.2.1 on 2023-07-14 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0011_2_7'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='street',
            new_name='street_1',
        ),
        migrations.AddField(
            model_name='company',
            name='assistant_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='current_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.subscription'),
        ),
        migrations.AddField(
            model_name='company',
            name='customer_stripe_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='street_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_doors',
            field=models.CharField(choices=[('1-50', '1-50'), ('50-200', '50-200'), ('200-500', '200-500'), ('500-1000', '500-1000'), ('1000-10,000', '1000-10,000'), ('10,000+', '10,000+')], max_length=16),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
