# Generated by Django 4.2.1 on 2023-06-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='street',
            new_name='street_1',
        ),
        migrations.AddField(
            model_name='company',
            name='street_2',
            field=models.CharField(default='apt 1', max_length=200),
            preserve_default=False,
        ),
    ]
