# Generated by Django 4.2.1 on 2023-08-06 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='point_of_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_of_contact_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
