# Generated by Django 4.2.1 on 2023-08-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_point_of_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='assistant_phone_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
