# Generated by Django 4.2.1 on 2023-06-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_street_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
