# Generated by Django 4.2.1 on 2023-06-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_stripe_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number_of_doors',
            field=models.CharField(choices=[(1, '1-50'), (2, '50-200'), (3, '200-500'), (4, '500-1000'), (5, '1000-10,000'), (6, '10,000+')], max_length=16),
        ),
    ]
