# Generated by Django 4.2.1 on 2023-06-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_company_number_of_doors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number_of_doors',
            field=models.CharField(choices=[('1-50', '1-50'), ('50-200', '50-200'), ('200-500', '200-500'), ('500-1000', '500-1000'), ('1000-10,000', '1000-10,000'), ('10,000+', '10,000+')], max_length=16),
        ),
    ]
