# Generated by Django 4.2.1 on 2023-06-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_company_number_of_doors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
