# Generated by Django 4.2.1 on 2023-07-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='assistant_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
