# Generated by Django 4.2.1 on 2023-07-08 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0011_2_7'),
        ('companies', '0010_company_assistant_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='company',
            name='current_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.subscription'),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.customer'),
        ),
    ]
