# Generated by Django 4.2.1 on 2023-07-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_remove_company_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='customer_stripe_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
