# Generated by Django 4.2.1 on 2023-07-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_company_customer_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='stripe_customer',
        ),
    ]
